name: Python package

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    services:
      postgres:
        image: postgres:13.4
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Sqlite Tests
      run: |
        JARDIN_CONF=tests/jardin_conf_sqlite.py python -m pytest tests

    - name: Run Postgresql Tests
      env:
        PGPASSWORD: postgres
      run: |
        psql --version
        psql -c 'create database jardin_test;' --host localhost --username postgres
        JARDIN_CONF=tests/jardin_conf_pg.py python -m pytest tests

    - name: Run Mysql Tests
      env:
        MYSQL_PWD: password
      run: |
        sudo apt-get install -y mysql-client
        mysql --version
        mysql -e 'create database jardin_test;' --host 127.0.0.1 --user root
        JARDIN_CONF=tests/jardin_conf_mysql.py python -m pytest tests